import React from 'react';
import {
  AppstoreOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CreditCardOutlined,
  DownloadOutlined,
  DollarOutlined,
  EyeOutlined,
  FileTextOutlined,
  FundOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartOutlined,
  HistoryOutlined,
  KeyOutlined,
  LineChartOutlined,
  LoadingOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  MessageOutlined,
  PartitionOutlined,
  PieChartOutlined,
  PlusOutlined,
  ProfileOutlined,
  QrcodeOutlined,
  ReloadOutlined,
  ReconciliationOutlined,
  SettingOutlined,
  SlidersOutlined,
  ShoppingCartOutlined,
  TagsOutlined,
  TeamOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  WalletOutlined,
  CloseOutlined,
  CopyOutlined,
  DashboardOutlined,
  DeleteOutlined,
  EditOutlined,
  RightOutlined,
  MoonOutlined,
  SunOutlined,
} from '@ant-design/icons';

const ICON_MAP = {
  bell: BellOutlined,
  book: BookOutlined,
  'chart bar': BarChartOutlined,
  'chart line': LineChartOutlined,
  'chart pie': PieChartOutlined,
  comments: MessageOutlined,
  'clipboard list': ReconciliationOutlined,
  close: CloseOutlined,
  check: CheckOutlined,
  'check circle': CheckCircleOutlined,
  'cloud upload': CloudUploadOutlined,
  cog: SettingOutlined,
  'copy outline': CopyOutlined,
  'credit card': CreditCardOutlined,
  cube: AppstoreOutlined,
  cubes: DashboardOutlined,
  'dollar sign': DollarOutlined,
  exchange: ReloadOutlined,
  edit: EditOutlined,
  download: DownloadOutlined,
  eye: EyeOutlined,
  'file alternate outline': FileTextOutlined,
  gift: GiftOutlined,
  global: GlobalOutlined,
  group: TeamOutlined,
  heartbeat: HeartOutlined,
  history: HistoryOutlined,
  key: KeyOutlined,
  language: GlobalOutlined,
  spinner: LoadingOutlined,
  'grid layout': AppstoreOutlined,
  'money bill alternate outline': FundOutlined,
  plus: PlusOutlined,
  qrcode: QrcodeOutlined,
  setting: SettingOutlined,
  'shopping cart': ShoppingCartOutlined,
  sidebar: MenuUnfoldOutlined,
  sitemap: PartitionOutlined,
  'sliders horizontal': SlidersOutlined,
  tags: TagsOutlined,
  tasks: ProfileOutlined,
  trash: DeleteOutlined,
  ticket: CheckCircleOutlined,
  'ticket alternate': CheckCircleOutlined,
  user: UserOutlined,
  users: UsergroupAddOutlined,
  'user circle': UserOutlined,
  wallet: WalletOutlined,
  'right chevron': RightOutlined,
  moon: MoonOutlined,
  sun: SunOutlined,
};

function AppIcon({ name = '', className = '' }) {
  const IconComponent = ICON_MAP[name] || ClusterOutlined;
  return <IconComponent className={className} />;
}

export default AppIcon;
